export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";

export const ESSENTIALS_LOADING = "ESSENTIALS_LOADING";
export const GET_ESSENTIALS = "GET_ESSENTIALS";
export const GET_ESSENTIAL = "GET_ESSENTIAL";
export const ADD_ESSENTIALS = "ADD_ESSENTIALS";
export const DELETE_ESSENTIALS = "DELETE_ESSENTIALS";

export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_ESADD_PROJECTENTIALS";
export const DELETE_PROJECT = "DELETE_PROJECT";
